[package]
name = "hash-sig-example"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9" # Or your preferred version
hashsig = { git = "https://github.com/b-wagn/hash-sig.git" }
signature = "3.0.0-rc.4"
bincode = { version = "2.0.1", features = ["serde"] }
